language: generic

install:
# install the package
- pip install --user schul_cloud_resources_server_tests

before_script:
# start the server you want to test
- python -m schul_cloud_resources_server_tests.app &
- sleep 1

script:
# test the server with the url and credentials
- python -m schul_cloud_resources_server_tests.tests --url=http://localhost:8080/v1 --basic=valid1@schul-cloud.org:123abc
